[template]
src = "bugzilla-ses-password.tmpl"
dest = "/etc/postfix/sasl_passwd"
prefix = "/%%STACK%%/%%ENVIRONMENT%%"

uid = 0
gid = 0
mode = "0600"

keys = [
    "/config"
]

reload_cmd = "/usr/sbin/postmap hash:/etc/postfix/sasl_passwd"
